using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.Shared.Entities.SISContext
{
    public partial class Studentbill
    {
        public Guid Id { get; set; }
        public string Studentid { get; set; }
        public int Programmestreamid { get; set; }
        public int? Feecategoryid { get; set; }
        public int Acadyear { get; set; }
        public int Sem { get; set; }
        public string Currencyid { get; set; }
        public DateTime Transdate { get; set; }
        public double Amount { get; set; }
        public double Xrate { get; set; }
        public string Narrative { get; set; }
        public DateTime Timeinserted { get; set; }
        public DateTime? Timeupdated { get; set; }
        public string Insertedby { get; set; }
        public string Updatedby { get; set; }
        public bool Autogenerated { get; set; }
        public int? Feetypeid { get; set; }
        public int? Residenceid { get; set; }
        public bool Iscommitted { get; set; }
        public DateTime? Transdate2 { get; set; }
    }
}
