USE [SIS]
GO

ALTER TABLE [dbo].[GRADINGSYSTEMSCORINGEXCEPTION]  WITH NOCHECK ADD  CONSTRAINT [FK_GRADINGSYSTEMSCORINGEXCEPTION_GRADINGSYSTEM] FOREIGN KEY([GRADINGID])
REFERENCES [dbo].[GRADINGSYSTEM] ([GRADINGID])
GO

ALTER TABLE [dbo].[GRADINGSYSTEMSCORINGEXCEPTION] CHECK CONSTRAINT [FK_GRADINGSYSTEMSCORINGEXCEPTION_GRADINGSYSTEM]
GO


